# Generated by Django 2.1.7 on 2019-03-25 20:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import photoset.features.enums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(photoset.features.enums.Gridtype('Stonework'), 'Stonework'), (photoset.features.enums.Gridtype('Tiles'), 'Tiles')], max_length=11)),
                ('width', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('gap', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=150, null=True, validators=[django.core.validators.URLValidator()])),
                ('description', models.TextField(max_length=400, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
